# fly.toml app configuration file generated for faithhub-backend on 2024-02-08T12:52:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'faithhub-backend'
primary_region = 'cdg'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  
  [mounts]
  source = "uploads"
  destination = "/uploads"